# Generated by Django 5.2.6 on 2025-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SystAdmin'), (2, 'ServiceProvider'), (3, 'Customer')], default=1),
        ),
    ]
